Repository rcore-os/rCore-Tutorial, pull requests merged in 2020-07, with the labels that each got.

#13 添加 GPLv3 协议
  LICENSE
Labels: important

#34 添加了 Gitalk 的部署
  book.json
  gitalk.html
Labels: documentation

#116 全自动化部署 GitHub Pages
  .github/workflows/deploy.yml
Labels: documentation, enhancement
